### PR TITLE
implement and use karatsuba square function

### PR DESCRIPTION
**Pull request by roynalnaruto**
Hello @kevaundray 

I used [this](https://github.com/otrv4/ed448/blob/master/karatsuba_square_32.go) as reference.

Best

### CODE REVIEW

**Comment by kevaundray** [comment]
Hey, 

Thanks for the PR. I saw this, but was not sure what has changed (See TODO), so I left it out

**Comment by roynalnaruto** [comment]
Are you referring to the comment I deleted?

I interpreted it as:
"Need to implement karatsuba square, and use it instead of karatsuba multiplication with both parameters set to be the same".

I believe the karatsuba square implementation is more optimised than passing `a` and `b` both the same in order to square `a`.

So I added the `square` function in `karatsuba.rs` and then modified `Fq::square` to use `karatsuba::square` instead of `karatsuba::mul` with both parameters the same.

This is my interpretation, your feedback would help :)

Thank you!

**Comment by kevaundray** [comment]
Hi, 

Yeah so this comment here: https://github.com/otrv4/ed448/blob/master/karatsuba_square_32.go#L3

I was not sure what exactly had changed, so I did not code it. Yep, the Karatsuba Square implementation will be faster than doing what I currently do, which is pass the same variable to Mul

**Comment by kevaundray** [comment]
In either case, I will merge now and review it once I do the second pass over the Field Arithmetic.

Thanks for the PR

**Comment by roynalnaruto** [comment]
> Hi,
> 
> Yeah so this comment here: https://github.com/otrv4/ed448/blob/master/karatsuba_square_32.go#L3
> 
> I was not sure what exactly had changed, so I did not code it. Yep, the Karatsuba Square implementation will be faster than doing what I currently do, which is pass the same variable to Mul

Oh! I missed that comment. No I don't know any more details on this comment.

**Pull request merged**
